Base
frontend-park-mail-ru/2022_1_CJ pull request #4
Opened 2022-03-26 16:24 UTC by senago

2022-03-29 19:08 UTC, alexey-ershkov requested changes
Посмотрел , отписал, в целом неплохо, но надо доводить до ума, плюс делайте мр с тем, что хотите, чтобы я посмотрел - не обязательно в мастер. Чтобы в диффе было 300-500 строк, но которые я внимательно смогу посмотреть, ибо тут оч много конфигов, верстки и прочего

2022-03-29 19:08 UTC, alexey-ershkov commented on .eslintrc.js
> +  // extends: ['eslint:recommended', 'plugin:import/recommended'],
Кажется это можно убрать

2022-03-29 19:08 UTC, alexey-ershkov commented on Dockerfile
> +# CMD ["nginx", "-g", "daemon off;"]
??

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/LoginForm/LoginForm.js
> +import { LoginUserDTO } from '../../core/network/dto/auth.js';
Опять DTO) Назовите без сокращений

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Menu/Menu.css
> +/* Menu starts */
Кажется лишнее - по названию файла и так понятно

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Menu/Menu.js
> +export const menuComponent = (template) => createComponent(template);
Кажется можно не писать подобный файлики, а сделать общий генератор

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.css
> +.info > p:first-child {
Опять же опираетесь на порядок и на html элементы

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.css
> +    /* animation: 3s ease-in 1s 2 reverse both paused slidein; */
???

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.css
> +/* .comments-list {
Комменты лучше все выпилить

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.handlebars
> +<<<<<<< HEAD
???

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.js
> +    switch (true) {
Что-то страшное - можно вынести в объект, но накиньте еще комментов, что здесь происходит, прям оч странно

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/Post/Post.js
> +  console.log(reply);
Консоль логов быть не должно

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/ProfileMenu/ProfileMenu.js
> +export const profileMenuComponent = (template) => createComponent(template);
Не могу написать к пустому файлу - у вас есть пустые файлы, зачем?

2022-03-29 19:08 UTC, alexey-ershkov commented on src/components/SignupForm/SignupForm.handlebars
> +</form>
нет переноса на новую строку в конце

2022-03-29 22:27 UTC, Similization commented on src/components/Post/Post.css
> +.info > p:first-child {
Это плохо ?

2022-03-29 22:28 UTC, Similization commented on src/components/Post/Post.css
> +/* .comments-list {
Комменты к посту или о чем речь ?

2022-03-29 22:28 UTC, Similization commented on src/components/Post/Post.handlebars
> +<<<<<<< HEAD
Тут что-то поехало

2022-03-29 22:43 UTC, Similization commented on src/components/Post/Post.js
> +    switch (true) {
В общем какая была идея
Я вывел +- адекватную формулу для вывода красивых лайков
В чем суть:
Лайки могут иметь следующий вид:
1
12
123
1k
1.23k
12.1k
723k
1.12m
и тд, но мы не рассчитываем на числа большие 999 миллионов, так что все просто

Общем первый if поверяет что число содержит менее 4 чисел -> оно отображается как обычно
Иначе мы его упрощаем
Что это значит ?
Если в числе 4 цифры, то мы делим его на 10**(1 == 4 - 3), округляем и делим на 10**(2 == 3*2 - 4) и получаем красивое число из трех цифр и одной точки (Пример 4782 лайка превратятся в 4.78)
Если в числе 5 цифр, то мы делим его на 10**(2 == 5 - 3), округляем и делим на 10**(1 == 3*2 - 5) и получаем красивое число из трех цифр и одной точки (Пример 47826 лайка превратятся в 47.8)
Если в числе 6 цифр, то мы делим его на 10**(3 == 6 - 3), округляем и делим на 10**(2 == 3*2 - 6) и получаем красивое число из трех цифр и одной точки (Пример 478265 лайка превратятся в 478)

Eсли цифр больше, то мы упрощаем число в соответствии с верхним алгоритмом: кол-во цифр в числе должно стать 4 если кол-во цифр % 3 == 1 
стать 5 если кол-во цифр % 3 == 2
стать 6 если кол-во цифр % 3 == 0
Math.round() округлит число до нужного кол-ва

Затем по старой длине мы определяем переписку 
'k', если число лежит в пределах [1.000; 1.000.000)
'm', если число лежит в пределах [1.000.000; 1.000.000.000)

2022-03-29 22:43 UTC, Similization commented on src/components/Post/Post.js
> +  console.log(reply);
Это для себя, потом все уберу

2022-03-30 14:29 UTC, Similization commented on src/components/ProfileMenu/ProfileMenu.js
> +export const profileMenuComponent = (template) => createComponent(template);
Это пока заготовка, потом навесим логику

2022-03-30 14:29 UTC, Similization commented on src/components/SignupForm/SignupForm.handlebars
> +</form>
Добавил

2022-03-30 14:29 UTC, Similization commented on src/components/Post/Post.css
> +    /* animation: 3s ease-in 1s 2 reverse both paused slidein; */
Не очевидно

2022-03-30 14:30 UTC, Similization commented on src/components/Menu/Menu.js
> +export const menuComponent = (template) => createComponent(template);
Да, но это не столь необходимо для 2 строчек кода

2022-03-30 14:30 UTC, Similization commented on src/components/Menu/Menu.css
> +/* Menu starts */
Убрал

2022-04-19 09:17 UTC, closed without merging